### ISSUE TITLE
queenbee.BaseModel may violate Python's data model

### ISSUE THREAD

**Issue by tymokvo** [pollination/queenbee#307]
While looking for an encapsulated way to get the hash/digest of a recipe for the registries service, I realized that `queenbee.BaseModel` implements the SHA256 of the package's JSON UTF8 string via the `__hash__` magic method. 

However, this seems to violate the [specification](https://docs.python.org/3.9/reference/datamodel.html#object.__hash__) of Python's data model which states:

> If a class does not define an `__eq__()` method it should not define a `__hash__()` operation either;

Modifying `__hash__` seems like a breaking change, so maybe `BaseModel` needs to define an appropriate `__eq__` method?

**Comment by tymokvo** [comment]
As a consumer, it might be nice to have a `.content_hash` property to differentiate between "the unique ID of the content of this object" and "the unique ID of this object in a Python program".

**Comment by mostaphaRoudsari** [comment]
This one is for @AntoineDao to comment on.

**Comment by AntoineDao** [comment]
Super late reply from me sorry 😅 The pydantic `BaseModel` does implement [`__eq__`](https://github.com/samuelcolvin/pydantic/blob/62bb2ad4921016df51abf3922c3fe51113b08939/pydantic/main.py#L914-L918) which we inherit from in all of our models. We overwrite the `__hash__` function through the class properties rather than as a [pydantic model meta class property](https://github.com/samuelcolvin/pydantic/blob/62bb2ad4921016df51abf3922c3fe51113b08939/pydantic/main.py#L238). I think this is ok for now as it makes it a bit more explicit but we could pass it through the meta class if you think it's cleaner 😀

**Comment by AntoineDao** [comment]
On an additional note it might be worth reviewing how we execute the `__hash__` function to ensure it behaves as we would expect it when managing package versions etc... We might benefit from a custom `digest` function for Plugins and Recipes which we use to calculate the integrity of the data inside the recipe without taking into account the `metadata` fields for example. We might also want to understand the `digest` behaviour when new default/empty fields are added to the Queenbee schema.

**Comment by AntoineDao** [comment]
I'm going to close this as it's stale. Feel free to re-open if we feel it needs resolving.
